/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author 835019
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setTitle("Controle de Paciente");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarPaciente = new javax.swing.JMenuItem();
        menuCadastrarAgendamento = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenu();
        MenuPesquisarPaciente = new javax.swing.JMenuItem();
        menuPesquisarAgendamento = new javax.swing.JMenuItem();
        menuEmail = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        menuCadastrar.setText("Cadastrar");

        menuCadastrarPaciente.setText("Paciente");
        menuCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarPacienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarPaciente);

        menuCadastrarAgendamento.setText("Agendamento");
        menuCadastrarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAgendamentoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAgendamento);

        jMenuBar1.add(menuCadastrar);

        menuPesquisar.setText("Pesquisar");

        MenuPesquisarPaciente.setText("Paciente");
        MenuPesquisarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesquisarPacienteActionPerformed(evt);
            }
        });
        menuPesquisar.add(MenuPesquisarPaciente);

        menuPesquisarAgendamento.setText("Agendamento");
        menuPesquisarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarAgendamentoActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarAgendamento);

        jMenuBar1.add(menuPesquisar);

        menuEmail.setText("Email");
        jMenuBar1.add(menuEmail);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areaTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(areaTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarPacienteActionPerformed
        abrirForm(new FormCadastroPaciente());
    }//GEN-LAST:event_menuCadastrarPacienteActionPerformed

    private void menuCadastrarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAgendamentoActionPerformed
       abrirForm(new FormCadastroAgendamento());
    }//GEN-LAST:event_menuCadastrarAgendamentoActionPerformed

    private void MenuPesquisarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesquisarPacienteActionPerformed
        
        abrirForm(new FormPesquisaPaciente());
    }//GEN-LAST:event_MenuPesquisarPacienteActionPerformed

    private void menuPesquisarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarAgendamentoActionPerformed
        abrirForm(new FormPesquisaAgendamento());
    }//GEN-LAST:event_menuPesquisarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuPesquisarPaciente;
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarAgendamento;
    private javax.swing.JMenuItem menuCadastrarPaciente;
    private javax.swing.JMenu menuEmail;
    private javax.swing.JMenu menuPesquisar;
    private javax.swing.JMenuItem menuPesquisarAgendamento;
    // End of variables declaration//GEN-END:variables

    private void abrirForm(JInternalFrame f){
        if (areaTrabalho.getAllFrames().length == 0){
            Dimension d = areaTrabalho.getSize();
            areaTrabalho.add(f);
            f.setLocation( (d.width-f.getSize().width)/2,
                           (d.height-f.getSize().height)/2);
            f.setVisible(true);
        }
    }
}
